name: Email Step Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f2003053@ds.study.iitm.ac.in
        run: echo "Hello, world!"
